name: Build OCI-Image with .NET 6
on:
  push:
    branches: [ main ]

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: devopenspace2022

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: 6.0.x
      - name: Restore Dependencies
        run: dotnet restore DemoApp/Server/src/Server.csproj
      - name: Build
        run: dotnet build DemoApp/Server/src/Server.csproj
      - name: Publish
        run: dotnet publish -c release -o DemoApp/Server/out DemoApp/Server/src/Server.csproj
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2.1.0
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}
          tags: |
           type=sha
           type=raw,value=v2.0.0
      
      - name: Build and push
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./DemoApp/Server
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
