name: Build .NET 6
on:
  push:
    branches: [ main ]

  workflow_dispatch:

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v3.0.2
        with:
          dotnet-version: 6.0.x
        
    
