name: Build OCI-Image with .NET 6
on:
  push:
    branches: [ main ]

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v3.0.2
        with:
          dotnet-version: 6.0.x
      - name: Restore Dependencies
        run: |
          dotnet restore DemoApp/Client/src/Client.csproj
          dotnet restore DemoApp/Server/src/Server.csproj
      - name: Build
        run: |
          dotnet build DemoApp/Client/src/Client.csproj
          dotnet build DemoApp/Server/src/Server.csproj
      - name: Publish
        run: |
          dotnet publish -c release -o out DemoApp/Client/src/Client.csproj
          dotnet publish -c release -o out DemoApp/Server/src/Server.csproj
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.0.1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
